version: "3"

services:
  database:
    container_name: keycloak-database
    image: postgres:13-alpine
    environment:
      POSTGRES_ROOT_PASSWORD: 12345678x@X
      POSTGRES_DATABASE: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./.docker/postgres_data_keycloak:/var/lib/postgresql/db
    ports:
      - "5433:5433"
    restart: unless-stopped
    networks:
      - vapeapp

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:16.1.0
    command: -b 0.0.0.0 -Dkeycloack.profile=preview
    restart: on-failure
    environment:
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/keycloak-server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/keycloak-server.key.pem
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: postgres
      DB_ADDR: database
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 12345678x@X
      REDIRECT_SOCKET: "proxy-https"
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    volumes:
      - ./.docker/keycloak-server.crt.pem:/opt/keycloak/conf/keycloak-server.crt.pem
      - ./.docker/keycloak-server.key.pem:/opt/keycloak/conf/keycloak-server.key.pem
    ports:
      - "9990:9990"
      - "9090:8080"
      - "8443:8443"
    networks:
      - vapeapp
    depends_on:
      - database

volumes:
  postgres_data_keycloak:
    driver: local

networks:
  vapeapp:
    driver: bridge
